// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using testapi1.Infrastructure.Persistence;

#nullable disable

namespace testapi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayerId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("testapi1.Domain.ActionCatalog", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IntentTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ProgressionEventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActionId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ActionCatalog");
                });

            modelBuilder.Entity("testapi1.Domain.DialogueTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TemplateId"));

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToneTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TemplateId");

                    b.HasIndex("ActionId");

                    b.HasIndex("NpcId", "ActionId", "ToneTag")
                        .IsUnique();

                    b.ToTable("DialogueTemplates");
                });

            modelBuilder.Entity("testapi1.Domain.Interaction", b =>
                {
                    b.Property<long>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InteractionId"));

                    b.Property<int?>("ChosenActionId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Friendliness")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NluTopIntent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<bool>("NsfwFlag")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutcomeFlags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RewardScore")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Sentiment")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<string>("ToneTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InteractionId");

                    b.HasIndex("ChosenActionId");

                    b.HasIndex("NpcId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId", "OccurredAt");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("testapi1.Domain.LoreChunk", b =>
                {
                    b.Property<int>("ChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChunkId"));

                    b.Property<string>("ChunkKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunkOrder")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChunkId");

                    b.HasIndex("ChunkKey")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("DocId", "ChunkOrder");

                    b.ToTable("LoreChunks");
                });

            modelBuilder.Entity("testapi1.Domain.LoreDoc", b =>
                {
                    b.Property<int>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DocId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("NpcId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("DocId");

                    b.HasIndex("DocKey")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("NpcId");

                    b.ToTable("LoreDocs");
                });

            modelBuilder.Entity("testapi1.Domain.Npc", b =>
                {
                    b.Property<int>("NpcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NpcId"));

                    b.Property<string>("Archetype")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BaseConfidence")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("BaseCuriosity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("BaseFriendliness")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("BaseOpenness")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("BasePatience")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NpcId");

                    b.HasIndex("NpcCode")
                        .IsUnique();

                    b.ToTable("Npcs");
                });

            modelBuilder.Entity("testapi1.Domain.PlayerNpcState", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("NpcId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Curiosity")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<DateTime>("LastInteractionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Openness")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("Patience")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("Trust")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.HasKey("PlayerId", "NpcId");

                    b.HasIndex("NpcId");

                    b.ToTable("PlayerNpcStates");
                });

            modelBuilder.Entity("testapi1.Domain.ProgressionStateAllowedAction", b =>
                {
                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ActionId")
                        .HasColumnType("integer");

                    b.HasKey("State", "ActionId");

                    b.HasIndex("ActionId");

                    b.ToTable("ProgressionStateAllowedActions");
                });

            modelBuilder.Entity("testapi1.Infrastructure.Persistence.ProgressionSessionEntity", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("CanConfess")
                        .HasColumnType("boolean");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClueClickHistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ComposureState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscoveredClueIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DiscussedClueIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ending")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<string>("LastTransitionReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NpcId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("PresentedEvidenceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProofTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ShutdownScore")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TrustScore")
                        .HasColumnType("integer");

                    b.Property<int>("TurnCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PlayerId", "UpdatedAtUtc");

                    b.ToTable("ProgressionSessions");
                });

            modelBuilder.Entity("testapi1.Domain.DialogueTemplate", b =>
                {
                    b.HasOne("testapi1.Domain.ActionCatalog", "Action")
                        .WithMany("DialogueTemplates")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("testapi1.Domain.Npc", "Npc")
                        .WithMany("DialogueTemplates")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("testapi1.Domain.Interaction", b =>
                {
                    b.HasOne("testapi1.Domain.ActionCatalog", "ChosenAction")
                        .WithMany("Interactions")
                        .HasForeignKey("ChosenActionId");

                    b.HasOne("testapi1.Domain.Npc", "Npc")
                        .WithMany("Interactions")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", "Player")
                        .WithMany("Interactions")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenAction");

                    b.Navigation("Npc");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("testapi1.Domain.LoreChunk", b =>
                {
                    b.HasOne("testapi1.Domain.LoreDoc", "Doc")
                        .WithMany("Chunks")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("testapi1.Domain.LoreDoc", b =>
                {
                    b.HasOne("testapi1.Domain.Npc", "Npc")
                        .WithMany("LoreDocs")
                        .HasForeignKey("NpcId");

                    b.Navigation("Npc");
                });

            modelBuilder.Entity("testapi1.Domain.PlayerNpcState", b =>
                {
                    b.HasOne("testapi1.Domain.Npc", "Npc")
                        .WithMany("PlayerStates")
                        .HasForeignKey("NpcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Player", "Player")
                        .WithMany("NpcStates")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Npc");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("testapi1.Domain.ProgressionStateAllowedAction", b =>
                {
                    b.HasOne("testapi1.Domain.ActionCatalog", "Action")
                        .WithMany("AllowedInStates")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");
                });

            modelBuilder.Entity("testapi1.Infrastructure.Persistence.ProgressionSessionEntity", b =>
                {
                    b.HasOne("Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Player", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("NpcStates");
                });

            modelBuilder.Entity("testapi1.Domain.ActionCatalog", b =>
                {
                    b.Navigation("AllowedInStates");

                    b.Navigation("DialogueTemplates");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("testapi1.Domain.LoreDoc", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("testapi1.Domain.Npc", b =>
                {
                    b.Navigation("DialogueTemplates");

                    b.Navigation("Interactions");

                    b.Navigation("LoreDocs");

                    b.Navigation("PlayerStates");
                });
#pragma warning restore 612, 618
        }
    }
}
